import { useMemo, useRef, useState } from "react";
import axios from "axios";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ChevronDown, Download, FileCheck2, Upload } from "lucide-react";
import api from "@/lib/api";
import { useAuthStore } from "@/stores/authStore";
import { useToast } from "@/hooks/use-toast";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import ReportTabs from "@/components/reports/ReportTabs";

type Version = { id: string; reference_year: number; reference_month: number; version: number; issued_on: string; active: boolean };
type Report = { id: string; reference_year: number; reference_month: number; version: number; issued_on: string; source: string; file_name: string; has_original: boolean; value_count: number; blank_count: number; imported_at: string; imported_by: string; values: Record<string, string>; };
type Result = { active: Report | null; versions: Version[]; can_edit: boolean; monthly_rates_available: boolean };
type Preview = { reference_year: number; reference_month: number; issued_on: string; page_count: number; value_count: number; blank_count: number; changed_count: number; changed_periods: string[]; next_version: number; sha256: string };

const monthShort = ["jan", "fev", "mar", "abr", "mai", "jun", "jul", "ago", "set", "out", "nov", "dez"];
const monthNames = ["janeiro", "fevereiro", "março", "abril", "maio", "junho", "julho", "agosto", "setembro", "outubro", "novembro", "dezembro"];
const period = (year: number, month: number) => `${monthNames[month - 1]}/${year}`;
const formatDate = (date: string) => new Date(`${date}T12:00:00`).toLocaleDateString("pt-BR");
const errorText = (error: unknown) => axios.isAxiosError(error) ? String(error.response?.data?.file?.[0] || error.response?.data?.token?.[0] || error.response?.data?.detail || "Tente novamente.") : "Tente novamente.";

export default function SelicReport() {
  const { isAdmin } = useAuthStore(); const { toast } = useToast(); const queryClient = useQueryClient();
  const fileRef = useRef<HTMLInputElement>(null);
  const [versionId, setVersionId] = useState(""); const [originYear, setOriginYear] = useState("2026"); const [originMonth, setOriginMonth] = useState("9");
  const [showImport, setShowImport] = useState(false); const [token, setToken] = useState(""); const [preview, setPreview] = useState<Preview | null>(null);
  const [correction, setCorrection] = useState<{ key: string; rate: string; reason: string } | null>(null);
  const query = useQuery({ queryKey: ["selic-reports", versionId], queryFn: async () => (await api.get<Result>("/dashboard/selic/", { params: versionId ? { report: versionId } : {} })).data });
  const report = query.data?.active; const years = useMemo(() => report ? Array.from({ length: report.reference_year - 1994 }, (_, i) => 1995 + i) : [], [report]);
  const selectedRate = report?.values[`${originYear}-${Number(originMonth).toString().padStart(2, "0")}`];

  const previewImport = useMutation({ mutationFn: async (file: File) => { const body = new FormData(); body.append("file", file); return (await api.post("/dashboard/selic/import/preview/", body)).data as { token: string; preview: Preview }; },
    onSuccess: data => { setToken(data.token); setPreview(data.preview); }, onError: error => toast({ title: "PDF não validado", description: errorText(error), variant: "destructive" }) });
  const confirmImport = useMutation({ mutationFn: () => api.post("/dashboard/selic/import/confirm/", { token }), onSuccess: () => { setToken(""); setPreview(null); setShowImport(false); setVersionId(""); void queryClient.invalidateQueries({ queryKey: ["selic-reports"] }); toast({ title: "Relatório confirmado", description: "O PDF e a nova versão foram preservados." }); }, onError: error => toast({ title: "Não foi possível confirmar", description: errorText(error), variant: "destructive" }) });
  const correct = useMutation({ mutationFn: () => api.patch(`/dashboard/selic/${report?.id}/${correction?.key.replace("-", "/")}/`, { rate: correction?.rate.replace(",", "."), reason: correction?.reason }), onSuccess: () => { setCorrection(null); setVersionId(""); void queryClient.invalidateQueries({ queryKey: ["selic-reports"] }); toast({ title: "Nova versão criada", description: "A taxa anterior continua no histórico." }); }, onError: error => toast({ title: "Correção não salva", description: errorText(error), variant: "destructive" }) });
  const download = async (url: string, name: string) => { try { const { data } = await api.get(url, { responseType: "blob" }); const href = URL.createObjectURL(data); const a = document.createElement("a"); a.href = href; a.download = name; a.click(); setTimeout(() => URL.revokeObjectURL(href), 1000); } catch { toast({ title: "Arquivo indisponível", variant: "destructive" }); } };

  return <div className="max-w-7xl mx-auto p-4 md:p-7 space-y-4">
    <style>{`@media print { header, footer, .no-print { display:none!important } .print-card { border:0!important; box-shadow:none!important } }`}</style>
    <ReportTabs />
    <div className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-2xl font-bold">Selic</h1><p className="text-sm text-muted-foreground">Relatórios oficiais do Sicalc, separados por competência de pagamento.</p></div>{isAdmin && <Button size="sm" onClick={() => { setShowImport(v => !v); setPreview(null); }}><Upload className="h-4 w-4 mr-2" />Importar PDF</Button>}</div>

    {showImport && isAdmin && <Card className="no-print border-primary/30"><CardContent className="p-4 space-y-3"><div><p className="font-semibold">1. Selecione o PDF oficial acumulado</p><p className="text-xs text-muted-foreground">O sistema valida tipo, referência, emissão, quantidade e divergências antes de salvar.</p></div><input ref={fileRef} type="file" accept="application/pdf" className="hidden" onChange={e => e.target.files?.[0] && previewImport.mutate(e.target.files[0])} /><Button size="sm" variant="outline" disabled={previewImport.isPending} onClick={() => fileRef.current?.click()}>{previewImport.isPending ? "Validando…" : "Escolher PDF"}</Button>{preview && <div className="rounded-md bg-muted p-3 text-sm space-y-2"><div className="flex items-center gap-2 font-semibold text-emerald-700"><FileCheck2 className="h-4 w-4" />PDF reconhecido</div><div className="grid grid-cols-2 md:grid-cols-5 gap-2"><span>Pagamento<br/><b>{period(preview.reference_year, preview.reference_month)}</b></span><span>Emissão<br/><b>{formatDate(preview.issued_on)}</b></span><span>Versão<br/><b>{preview.next_version}</b></span><span>Valores<br/><b>{preview.value_count}</b></span><span>Divergências<br/><b>{preview.changed_count}</b></span></div>{preview.changed_count > 0 && <p className="text-amber-700">Diferenças encontradas: {preview.changed_periods.join(", ")}{preview.changed_count > 20 ? "…" : ""}</p>}<div className="flex justify-end gap-2"><Button size="sm" variant="ghost" onClick={() => { setPreview(null); setToken(""); }}>Cancelar</Button><Button size="sm" disabled={confirmImport.isPending} onClick={() => confirmImport.mutate()}>{confirmImport.isPending ? "Salvando…" : "Confirmar e salvar"}</Button></div></div>}</CardContent></Card>}

    {query.isError && <div className="rounded-md border border-destructive p-3 text-destructive">Não foi possível carregar os relatórios Selic.</div>}
    {report && <>
      <Card><CardContent className="p-4"><div className="grid gap-4 md:grid-cols-[1fr_auto] md:items-center"><div><p className="text-xs uppercase tracking-wide text-muted-foreground">Relatório em consulta</p><p className="text-xl font-bold">Pagamento em {period(report.reference_year, report.reference_month)}</p><p className="text-sm text-muted-foreground">Emitido em {formatDate(report.issued_on)} · versão {report.version} · {report.value_count} taxas</p></div><div className="flex flex-wrap gap-2 no-print"><select aria-label="Versão do relatório" className="h-9 rounded-md border bg-background px-3 text-sm" value={versionId || report.id} onChange={e => { setVersionId(e.target.value); }}>{query.data?.versions.map(v => <option key={v.id} value={v.id}>{period(v.reference_year, v.reference_month)} · v{v.version}{v.active ? " (ativa)" : ""}</option>)}</select><Button size="sm" variant="outline" onClick={() => download(`/dashboard/selic/?report=${report.id}&export=csv`, `selic-${report.reference_year}-${report.reference_month}.csv`)}><Download className="h-4 w-4 mr-1"/>CSV</Button>{report.has_original && <Button size="sm" variant="outline" onClick={() => download(`/dashboard/selic/${report.id}/original/`, report.file_name)}>PDF original</Button>}</div></div></CardContent></Card>

      <div className="grid md:grid-cols-2 gap-4"><Card><CardContent className="p-4 space-y-3"><div><p className="font-semibold">Consulta rápida</p><p className="text-xs text-muted-foreground">Escolha o mês de origem da dívida.</p></div><div className="grid grid-cols-2 gap-2"><div><Label>Ano</Label><select className="h-9 w-full rounded-md border bg-background px-3" value={originYear} onChange={e => setOriginYear(e.target.value)}>{years.map(year => <option key={year}>{year}</option>)}</select></div><div><Label>Mês</Label><select className="h-9 w-full rounded-md border bg-background px-3" value={originMonth} onChange={e => setOriginMonth(e.target.value)}>{monthNames.map((name, index) => <option key={name} value={index + 1}>{name}</option>)}</select></div></div><div className="rounded-md bg-primary/5 p-3"><p className="text-xs text-muted-foreground">Taxa acumulada para pagamento em {period(report.reference_year, report.reference_month)}</p><p className="text-2xl font-bold">{selectedRate === undefined ? "Sem valor" : `${Number(selectedRate).toLocaleString("pt-BR", { minimumFractionDigits: 2 })}%`}</p></div></CardContent></Card>
      <Card><CardContent className="p-4 space-y-2"><p className="font-semibold">Taxas mensais oficiais</p><p className="text-sm text-muted-foreground">Ainda não importadas. A tabela acumulada não será usada para inventar ou reconstruir taxas mensais.</p><p className="text-xs rounded bg-amber-50 text-amber-800 p-2">Para calcular atualizações por soma mensal com segurança, será necessário fornecer o PDF oficial de taxas mensais.</p></CardContent></Card></div>

      <details className="group rounded-lg border bg-card print-card" open><summary className="flex cursor-pointer list-none items-center justify-between p-4 font-semibold">Tabela completa <ChevronDown className="h-4 w-4 transition group-open:rotate-180" /></summary><div className="overflow-x-auto border-t"><table className="w-full text-xs text-right"><thead><tr className="bg-muted/50"><th className="p-2 text-left sticky left-0 bg-muted">Ano</th>{monthShort.map(m => <th key={m} className="p-2 uppercase">{m}</th>)}</tr></thead><tbody>{years.map(year => <tr key={year} className="border-t"><th className="p-2 text-left sticky left-0 bg-card">{year}</th>{monthShort.map((_, index) => { const key = `${year}-${String(index + 1).padStart(2, "0")}`; const value = report.values[key]; return <td key={key} className="p-2">{value === undefined ? <span className="text-muted-foreground" title="Sem valor publicado">—</span> : <button className={isAdmin ? "underline decoration-dotted hover:text-primary" : "cursor-default"} disabled={!isAdmin} title={isAdmin ? "Criar correção auditada" : undefined} onClick={() => setCorrection({ key, rate: value.replace(".", ","), reason: "" })}>{Number(value).toLocaleString("pt-BR", { minimumFractionDigits: 2 })}</button>}</td>; })}</tr>)}</tbody></table></div><p className="p-3 text-xs text-muted-foreground border-t">— significa ausência de valor publicado; 0,00 é uma taxa oficial válida.</p></details>
    </>}

    {correction && report && <div className="fixed inset-0 z-50 grid place-items-center bg-black/40 p-4 no-print"><Card className="w-full max-w-md"><CardContent className="p-5 space-y-4"><div><p className="font-semibold">Correção auditada · {correction.key}</p><p className="text-xs text-muted-foreground">Será criada uma nova versão; a anterior será preservada.</p></div><div><Label>Nova taxa (%)</Label><Input value={correction.rate} onChange={e => setCorrection({ ...correction, rate: e.target.value })}/></div><div><Label>Justificativa obrigatória</Label><Input value={correction.reason} onChange={e => setCorrection({ ...correction, reason: e.target.value })} placeholder="Informe o motivo e a fonte da correção"/></div><div className="flex justify-end gap-2"><Button variant="ghost" onClick={() => setCorrection(null)}>Cancelar</Button><Button disabled={correction.reason.trim().length < 5 || correct.isPending} onClick={() => correct.mutate()}>{correct.isPending ? "Salvando…" : "Criar versão"}</Button></div></CardContent></Card></div>}
  </div>;
}
